apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "spring-boot-camel-xa"
roleRef:
  # Add the edit role to the service account
  name: "edit"
subjects:
  - kind: "ServiceAccount"
    name: "spring-boot-camel-xa"